# Generated by Django 5.0.1 on 2024-02-21 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        ('slots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_id', models.CharField(editable=False, max_length=36, unique=True, verbose_name='rent_id')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('lat', models.CharField(max_length=150)),
                ('lng', models.CharField(max_length=150)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike', to='bikes.bike')),
                ('collection_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_slot', to='slots.slot')),
                ('return_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_slot', to='slots.slot')),
            ],
        ),
    ]
