# Generated by Django 5.0.1 on 2024-02-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='rent_id',
            field=models.CharField(default=0, editable=False, max_length=36, unique=True, verbose_name='rent_id'),
            preserve_default=False,
        ),
    ]
