# Generated by Django 5.0.1 on 2024-02-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rent_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
