# Generated by Django 5.0.1 on 2024-02-21 10:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id_payment', models.CharField(editable=False, max_length=36, primary_key=True, serialize=False, unique=True, verbose_name='pi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Payout',
            },
        ),
    ]
