version: "3.9"

services:
  frontend-react:
    build:
      context: ./frontend
    container_name: frontend_react
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - practica_net

  djangoapp:
    container_name: djangoapp
    build:
      context: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - ./backend/bk:/app_django/bk
    ports:
      - "8000:8000"
    environment:
      - PG_USER=kevin
      - PG_PASSWORD=1234
      - PG_DB=trailblaze
      - PG_PORT=5432
      - PG_HOST=local_pgdb
    depends_on:
      - db
    networks:
      - practica_net

  db:
    image: postgres:15
    container_name: local_pgdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "kevin"
      POSTGRES_PASSWORD: 1234
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./backend/bk/exportacion.sql:/docker-entrypoint-initdb.d/db_init.sql
    networks:
      - practica_net 

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kevin@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: 1234
      PGADMIN_DEFAULT_SERVER: db
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - djangoapp
    networks:
      - practica_net

  loadbalancer:
    image: nginx:latest
    container_name: nginx_loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/nginx.conf:ro
    command: ["nginx", "-g", "daemon off;"]
    entrypoint: []
    depends_on:
      - djangoapp
    networks:
      - practica_net

  prometheus:
    image: prom/prometheus
    volumes:
      - ./backend/prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"
    depends_on:
      - djangoapp
    networks:
      - practica_net


volumes:
  local_pgdata:
  pgadmin-data:

networks:
  practica_net: {}
