version: "3.9"

services:
  frontend-react:
    build:
      context: ./frontend
    container_name: frontend_react
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

  djangoapp:
    container_name: djangoapp
    build:
      context: ./backend
    restart: unless-stopped
    volumes:
      - ./backend:/app
      # - ./backend:/code/backend
    ports:
      - "8000:8000"
    environment:
      - PG_USER=kevin
      - PG_PASSWORD=1234
      - PG_DB=trailblaze
      - PG_PORT=5432
      - PG_HOST=local_pgdb
    depends_on:
      - db

  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "kevin"
      POSTGRES_PASSWORD: 1234
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./db/db_init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kevin@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data:
