# Generated by Django 5.0.1 on 2024-01-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0006_alter_station_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station',
            table='Station',
        ),
    ]
