#Generated by Django 5.0.1 on 2024-01-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0007_alter_station_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
    ]