# Generated by Django 5.0.1 on 2024-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0008_alter_station_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='status',
            field=models.CharField(default='valorpordefecto', max_length=100),
            preserve_default=False,
        ),
    ]
