# Generated by Django 5.0.1 on 2024-02-15 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0009_station_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
