# Generated by Django 5.0.1 on 2024-02-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0010_alter_station_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='image',
            field=models.CharField(max_length=3000),
        ),
    ]
